### ISSUE TITLE
Docker installation not working on Raspbian Buster

### ISSUE THREAD

**Issue by thunder2k** [jaymoulin/google-musicmanager-dedup-api#1]
Hi,
the code in the homepage to install docker and pull your image is not working on Raspian Buster.

I run this:
`curl -sSL "https://gist.githubusercontent.com/jaymoulin/e749a189511cd965f45919f2f99e45f3/raw/0e650b38fde684c4ac534b254099d6d5543375f1/ARM%2520(Raspberry%2520PI)%2520Docker%2520Install" | sudo sh && sudo usermod -aG docker $USER`

And got this output:
`Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.64.0-4).
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
# Executing docker install script, commit: 2f4ae48
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian 10 stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
E: The repository 'https://download.docker.com/linux/raspbian 10 Release' does not have a Release file.`

Any hints on how to fix this?

Thanks!

**Comment by jaymoulin** [comment]
This is not related to this project but to docker. (https://github.com/moby/moby/issues maybe)

Looks like this raspbian version is not supported by docker. You should try by upgrading your raspbian version or `apt-get update && apt-get install docker-ce -y` but I can't guarantee anything

**Comment by jaymoulin** [comment]
Somebody already has your issue: https://github.com/moby/moby/issues/39417

https://blog.alexellis.io/how-to-fix-docker-for-raspbian-buster/

**Comment by thunder2k** [comment]
Thanks a lot, I already figured it out and installed it manually. Didn't know I had to reboot and I was going mad hahaha
